### ISSUE TITLE
factor_multiply issues

### ISSUE THREAD

**Issue by kiranvodrahalli** [HazyResearch/learning-circuits#1]
Hello, 

I was trying to run your experiments -- currently, it seems like there are issues with importing the functions from factor_multiply -- After following the instructions to compile the factor_multiply module, I try to run the experiments and get: 
ImportError: cannot import name 'butterfly_factor_multiply' from 'factor_multiply' (unknown location)

So I decided to try to work around this by using your old code rather than (what seems to be the newer) factor_multiply versions of things. This almost worked -- There seems to be a shape issue on line 572 of butterfly.py (arises when I try running the first DFT experiment in run_exp.sh, the 8x8 one). 

Would appreciate any advice!

Thanks.

**Comment by tridao** [comment]
Thanks for trying our code. The `butterfly` directory should be stable, but the `learning_transforms` directory is a bit unstable at the moment since we're refactoring. Our apologies. 
I've just updated the instruction to install C++ extension for Pytorch. Can you try it with the new instruction? 
I don't have access to our server at the moment so I can't test it, but I hope it can help with the `ImportError`. I'll test it more thoroughly tomorrow morning.

**Comment by kiranvodrahalli** [comment]
Thanks! This indeed fixes the import problem. No worries about the refactoring.
